In [1]:
import pandas as pd
import numpy as np
import torch
from sklearn.preprocessing import StandardScaler

In [2]:
dataset = pd.read_csv("C:/Users/Admin/Desktop/Coding/Tensorflow/Carprice.csv")
dataset = dataset.drop(["car_ID","CarName"], axis=1).dropna()
dataset["price"] = dataset["price"]/10000
label = dataset["price"]
feature = dataset.drop("price",axis=1)
feature = pd.get_dummies(feature)


In [3]:
features = np.array(feature)
labels = np.array(label).reshape(-1,1)
features = StandardScaler().fit_transform(features)
features = torch.tensor(features, dtype = torch.float32)
labels = torch.tensor(labels,dtype = torch.float32)

C:\Users\Admin\AppData\Local\Temp\ipykernel_7948\1505966717.py:4: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  features = torch.tensor(features, dtype = torch.float32)


In [4]:
model = torch.nn.Linear(52,1)
preds=model(features)


In [5]:
from torch.nn.functional import mse_loss

loss  = mse_loss(preds, labels)
print(loss)

loss.backward()

print(model.weight.grad)
print(model.bias.grad)

tensor(3.0648, grad_fn=<MseLossBackward0>)
tensor([[ 0.8889, -1.4590, -1.3470, -1.2740, -1.1729, -1.3048, -0.9809, -0.6236,
         -0.3129, -0.8586, -0.3857,  0.9050,  0.5402,  0.6960, -0.9587,  0.9587,
          0.4945, -0.4945, -0.8847,  0.8847, -0.2014,  0.0787,  0.9278, -0.4746,
         -0.5635, -0.1576,  0.7931, -0.7421, -0.2735,  0.2735,  0.1576,  0.1380,
         -0.4394, -0.0229,  0.3470, -0.2659,  0.2982, -0.5848, -0.8006,  0.6408,
         -0.1186,  0.0324, -0.0297,  0.2982,  0.2127,  0.5870,  0.2868, -0.9587,
          0.1964, -0.3237,  0.3369,  0.0918]])
tensor([-2.9142])


In [6]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

optimizer.step()
optimizer.zero_grad()

preds = model(features)
loss = mse_loss(preds, labels)
print(loss)

tensor(3.0328, grad_fn=<MseLossBackward0>)


In [7]:
epochs = 15000
for epoch in range(epochs):
    preds = model(features)
    loss = mse_loss(preds, labels)
    
    if (epoch+1)%1000 == 0:
        print(loss)

    loss.backward()
    
    optimizer.step()
    optimizer.zero_grad()


tensor(0.1037, grad_fn=<MseLossBackward0>)
tensor(0.0507, grad_fn=<MseLossBackward0>)
tensor(0.0455, grad_fn=<MseLossBackward0>)
tensor(0.0435, grad_fn=<MseLossBackward0>)
tensor(0.0425, grad_fn=<MseLossBackward0>)
tensor(0.0418, grad_fn=<MseLossBackward0>)
tensor(0.0414, grad_fn=<MseLossBackward0>)
tensor(0.0411, grad_fn=<MseLossBackward0>)
tensor(0.0408, grad_fn=<MseLossBackward0>)
tensor(0.0406, grad_fn=<MseLossBackward0>)
tensor(0.0404, grad_fn=<MseLossBackward0>)
tensor(0.0402, grad_fn=<MseLossBackward0>)
tensor(0.0401, grad_fn=<MseLossBackward0>)
tensor(0.0400, grad_fn=<MseLossBackward0>)
tensor(0.0399, grad_fn=<MseLossBackward0>)


In [12]:
x = 87
preds = model(features[x])
print(preds*10000,labels[x]*10000)

tensor([10371.4805], grad_fn=<MulBackward0>) tensor([9279.])
