# CAR PRICE CLASSIFICATION

In [33]:
import pandas as pd
import numpy as np
import torch
from sklearn.preprocessing import StandardScaler

**Assigning Features & Labels**

In [34]:
dataset = pd.read_csv("C:/Users/Admin/Desktop/Coding/Tensorflow/Carprice.csv")
dataset = dataset.drop(["car_ID","CarName"], axis=1).dropna()
dataset["price"] = dataset["price"]/10000
label = dataset["price"]
feature = dataset.drop("price",axis=1)
feature = pd.get_dummies(feature)


In [35]:
features = np.array(feature)
labels = np.array(label).reshape(-1,1)
features = StandardScaler().fit_transform(features)
features = torch.tensor(features, dtype = torch.float32)
labels = torch.tensor(labels,dtype = torch.float32)

In [36]:
model = torch.nn.Linear(52,1)
preds=model(features)


*Predicting the Weight & bias*

In [37]:
from torch.nn.functional import mse_loss

loss  = mse_loss(preds, labels)
print(loss)

loss.backward()

print(model.weight.grad)
print(model.bias.grad)

tensor(2.3785, grad_fn=<MseLossBackward0>)
tensor([[-0.3694,  0.0039, -0.2620, -0.4496,  0.4202, -0.4852, -0.8978, -0.2618,
          0.0615,  0.5439, -0.9662, -0.5338,  0.7931,  0.6977,  0.5945, -0.5945,
         -0.5423,  0.5423,  0.3592, -0.3592, -0.2773, -0.5799,  0.0519,  0.1176,
          0.2314,  0.2541,  0.3580, -0.4730,  1.0018, -1.0018, -0.0353, -0.0606,
          0.5471,  0.2856, -0.2237, -0.5366, -0.3965, -0.4730, -0.2627,  1.1089,
         -0.8188,  0.2279, -0.4051, -0.3965, -0.1083,  0.2738, -0.3845,  0.5945,
          0.1684, -0.5623,  0.1238,  0.1340]])
tensor([-2.5501])


In [38]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)

optimizer.step()
optimizer.zero_grad()

preds = model(features)
loss = mse_loss(preds, labels)
print(loss)

tensor(2.3589, grad_fn=<MseLossBackward0>)


## Training Loop

In [39]:
epochs = 15000
for epoch in range(epochs):
    preds = model(features)
    loss = mse_loss(preds, labels)
    
    if (epoch+1)%1000 == 0:
        print(loss)

    loss.backward()
    
    optimizer.step()
    optimizer.zero_grad()


tensor(0.0892, grad_fn=<MseLossBackward0>)
tensor(0.0505, grad_fn=<MseLossBackward0>)
tensor(0.0464, grad_fn=<MseLossBackward0>)
tensor(0.0445, grad_fn=<MseLossBackward0>)
tensor(0.0434, grad_fn=<MseLossBackward0>)
tensor(0.0426, grad_fn=<MseLossBackward0>)
tensor(0.0420, grad_fn=<MseLossBackward0>)
tensor(0.0416, grad_fn=<MseLossBackward0>)


### Result

In [ ]:
x = 87
preds = model(features[x])
print(preds*10000,labels[x]*10000)

tensor([10280.1768], grad_fn=<MulBackward0>) tensor([9279.])
