In [1]:
import pandas as pd
import numpy as np
import torch
from sklearn.preprocessing import StandardScaler
from torch.nn.functional import mse_loss

In [2]:
dataset = pd.read_csv("C:/Users/Admin/Desktop/Coding/Tensorflow/Mobiledataset.csv")
dataset = dataset.drop(["model","base_color","processor"], axis=1)
dataset["battery_capacity"] = dataset["battery_capacity"]/1000
dataset["num_of_ratings"] = dataset["num_of_ratings"]/10000
dataset["sales_price"] = dataset["sales_price"]/1000
dataset["ROM"] = dataset["ROM"]/100
label = dataset["sales"]
feature = dataset.drop("sales",axis=1)
feature = pd.get_dummies(feature)

In [3]:
features = np.array(feature)
labels = np.array(label).reshape(-1,1)
features = StandardScaler().fit_transform(features)
features = torch.tensor(features, dtype = torch.float32)
labels = torch.tensor(labels,dtype = torch.float32)
print(features.shape, labels.shape)
print(features)

torch.Size([430, 20]) torch.Size([430, 1])
tensor([[-0.6617, -1.5233, -4.5237,  ..., -0.2930, -0.0969, 10.3199],
        [-0.6617, -0.6059, -2.6272,  ...,  3.4128, -0.0969, -0.0969],
        [-0.6617, -1.5233, -4.5237,  ..., -0.2930, -0.0969, 10.3199],
        ...,
        [ 0.3527,  0.3115,  0.3528,  ..., -0.2930, -0.0969, -0.0969],
        [-1.1689, -1.0646, -0.4599,  ..., -0.2930, -0.0969, -0.0969],
        [-1.1689, -1.0646, -1.5436,  ...,  3.4128, -0.0969, -0.0969]])


C:\Users\Admin\AppData\Local\Temp\ipykernel_9180\433068428.py:4: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  features = torch.tensor(features, dtype = torch.float32)


In [4]:
model = torch.nn.Sequential(
    torch.nn.Linear(20,10),
    torch.nn.LeakyReLU(), # activation functions
    torch.nn.Linear(10,6),
    torch.nn.ReLU(),
    torch.nn.Linear(6,9),
    torch.nn.ReLU(),
    torch.nn.Linear(9,1)
)

preds = model(features)
print(preds.shape)

print(preds)


torch.Size([430, 1])
tensor([[0.3836],
        [0.2815],
        [0.3836],
        [0.2425],
        [0.2425],
        [0.2400],
        [0.2425],
        [0.2400],
        [0.2425],
        [0.2425],
        [0.2815],
        [0.2425],
        [0.2839],
        [0.2522],
        [0.2839],
        [0.2435],
        [0.2400],
        [0.2400],
        [0.2815],
        [0.2522],
        [0.2906],
        [0.2435],
        [0.2522],
        [0.2400],
        [0.2435],
        [0.2435],
        [0.2522],
        [0.2425],
        [0.2815],
        [0.2435],
        [0.2815],
        [0.2839],
        [0.3041],
        [0.2425],
        [0.2906],
        [0.3836],
        [0.2906],
        [0.2906],
        [0.2839],
        [0.2906],
        [0.2839],
        [0.2655],
        [0.3689],
        [0.2504],
        [0.2435],
        [0.2435],
        [0.2435],
        [0.2425],
        [0.2425],
        [0.2425],
        [0.2425],
        [0.2435],
        [0.2469],
        [0.2425],
       

In [5]:
loss = mse_loss(preds, labels)
loss

tensor(4273.2583, grad_fn=<MseLossBackward0>)

In [6]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)


In [15]:
epochs = 15000
for epoch in range(epochs):
    preds = model(features)
    loss = mse_loss(preds, labels)
    
    if (epoch+1)%(epochs//10) == 0:
        print(loss)

    loss.backward()
    
    optimizer.step()
    optimizer.zero_grad()

tensor(1.4360, grad_fn=<MseLossBackward0>)
tensor(2.2020, grad_fn=<MseLossBackward0>)
tensor(1.4040, grad_fn=<MseLossBackward0>)
tensor(1.7969, grad_fn=<MseLossBackward0>)
tensor(1.4138, grad_fn=<MseLossBackward0>)
tensor(1.7770, grad_fn=<MseLossBackward0>)
tensor(1.9818, grad_fn=<MseLossBackward0>)
tensor(1.4754, grad_fn=<MseLossBackward0>)
tensor(1.1245, grad_fn=<MseLossBackward0>)
tensor(1.4652, grad_fn=<MseLossBackward0>)


In [17]:
x = 100
preds = model(features[x])
print(preds,labels[x])

tensor([50.4977], grad_fn=<AddBackward0>) tensor([50.0400])
